task: dockerize and update node
XervoIO/simple-queue pull request #2
Opened 2017-03-16 02:20 UTC by theworkflow

- Dockerize service using `node@6.10`
- Lint code

2017-03-16 02:40 UTC, jackboberg commented on docker-compose.yml
> +      NODE_ENV: DEVELOPMENT
why uppercased?

2017-03-16 03:17 UTC, theworkflow commented on docker-compose.yml
> +      NODE_ENV: DEVELOPMENT
didn't think about it when i was typing. i can do lowercase

2017-03-16 13:14 UTC, jackboberg requested changes

2017-03-16 13:14 UTC, jackboberg commented on .env.example
> +
add `QUEUE_PORT`

2017-03-16 13:16 UTC, jackboberg commented on Dockerfile
> +
add `EXPOSE 80`

2017-03-16 18:48 UTC, jackboberg approved these changes

2017-03-16 19:17 UTC, bsatrom approved these changes

2017-03-17 16:56 UTC, jackboberg approved these changes

2017-03-17 18:53 UTC, merged